services:

  angularbibliotecavirtual:
    image: nginx:1.23.2-alpine
    container_name: angularbibliotecavirtual
    restart: unless-stopped
    working_dir: /usr/share/nginx/html
    ports:
      - 4195:4195
    networks:
      - laravel-net
    volumes:
      - ./frontend/BibliotecaPortalWeb/dist/mi-app/browser:/usr/share/nginx/html
      - ./frontend/BibliotecaPortalWeb/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
 laravel-net:
    external: true
